# Permalinks
permalink:           pretty

# Setup
title:               Tiago Ramalho
tagline:             'AI research in Tokyo'
description:         >- # this means to ignore newlines until "baseurl:"
                      Building AI for sustainability at <a href="https://recursiveai.co.jp/en">Recursive</a>.
                      I used to be a Research Engineering Manager at Google Deepmind, and a
                      Research Scientist at Cogent Labs.
                      I love to cook and go on long hikes. Currently based in Tokyo.

url:                 'https://tmramalho.github.io'
baseurl:             ''
paginate:            5
twitter_username: tmramalho
github_username:  tmramalho
linkedin_username: tiago-ramalho-526140b3

# About/contact
author:
  name:              Tiago Ramalho
  url:               https://twitter.com/tmramalho
  email:             tiago@nehalemlabs.net

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      image: "/images/global/cover.jpg"
