# Permalinks
permalink:           pretty

# Setup
title:               Tiago Ramalho
tagline:             'AI research in Tokyo'
description:         >- # this means to ignore newlines until "baseurl:"
                      I am currently a Research Scientist at Cogent Labs.
                      Previously a Research Engineer at DeepMind.
url:                 'https://tmramalho.github.io'
baseurl:             ''
paginate:            5
twitter_username: tmramalho
github_username:  tmramalho

# About/contact
author:
  name:              Tiago Ramalho
  url:               https://twitter.com/tmramalho
  email:             tiago@nehalemlabs.net

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      image: "/images/global/cover.jpg"
